INSERT INTO Occupation (occCode, occName) VALUES ('11', '공공 기관 및 기업 고위직');
INSERT INTO Occupation (occCode, occName) VALUES ('12', '행정·경영 지원 및 마케팅 관리직');
INSERT INTO Occupation (occCode, occName) VALUES ('13', '전문 서비스 관리직');
INSERT INTO Occupation (occCode, occName) VALUES ('14', '건설·전기 및 생산 관련 관리직');
INSERT INTO Occupation (occCode, occName) VALUES ('15', '판매 및 고객 서비스 관리직');
INSERT INTO Occupation (occCode, occName) VALUES ('21', '과학 전문가 및 관련직');
INSERT INTO Occupation (occCode, occName) VALUES ('22', '정보 통신 전문가 및 기술직');
INSERT INTO Occupation (occCode, occName) VALUES ('23', '공학 전문가 및 기술직');
INSERT INTO Occupation (occCode, occName) VALUES ('24', '보건·사회복지 및 종교 관련직');
INSERT INTO Occupation (occCode, occName) VALUES ('25', '교육 전문가 및 관련직');
INSERT INTO Occupation (occCode, occName) VALUES ('26', '법률 및 행정 전문직');
INSERT INTO Occupation (occCode, occName) VALUES ('27', '경영·금융전문가 및 관련직');
INSERT INTO Occupation (occCode, occName) VALUES ('28', '문화·예술·스포츠 전문가 및 관련직');
INSERT INTO Occupation (occCode, occName) VALUES ('31', '경영 및 회계 관련 사무직');
INSERT INTO Occupation (occCode, occName) VALUES ('32', '금융 및 보험 사무직');
INSERT INTO Occupation (occCode, occName) VALUES ('33', '법률 및 감사 사무직');
INSERT INTO Occupation (occCode, occName) VALUES ('39', '상담·안내·통계 및 기타 사무직');
INSERT INTO Occupation (occCode, occName) VALUES ('41', '경찰·소방 및 보안관련 서비스직');
INSERT INTO Occupation (occCode, occName) VALUES ('42', '이미용·예식 및 의료보조 서비스직');
INSERT INTO Occupation (occCode, occName) VALUES ('43', '운송 및 여가 서비스직');
INSERT INTO Occupation (occCode, occName) VALUES ('44', '조리 및 음식서비스직');
INSERT INTO Occupation (occCode, occName) VALUES ('51', '영업직');
INSERT INTO Occupation (occCode, occName) VALUES ('52', '매장 판매직');
INSERT INTO Occupation (occCode, occName) VALUES ('53', '방문·노점 및 통신판매 관련직');
INSERT INTO Occupation (occCode, occName) VALUES ('61', '농·축산 숙련직');
INSERT INTO Occupation (occCode, occName) VALUES ('62', '임업 숙련직');
INSERT INTO Occupation (occCode, occName) VALUES ('63', '어업 숙련직');
INSERT INTO Occupation (occCode, occName) VALUES ('71', '식품가공 관련 기능직');
INSERT INTO Occupation (occCode, occName) VALUES ('72', '섬유·의복 및 가죽 관련 기능직');
INSERT INTO Occupation (occCode, occName) VALUES ('73', '목재·가구·악기 및 간판 관련 기능직');
INSERT INTO Occupation (occCode, occName) VALUES ('74', '금속성형 관련 기능직');
INSERT INTO Occupation (occCode, occName) VALUES ('75', '운송 및 기계 관련 기능직');
INSERT INTO Occupation (occCode, occName) VALUES ('76', '전기 및 전자 관련 기능직');
INSERT INTO Occupation (occCode, occName) VALUES ('77', '건설 및 채굴 관련 기능직');
INSERT INTO Occupation (occCode, occName) VALUES ('78', '영상 및 통신장비 관련 기능직');
INSERT INTO Occupation (occCode, occName) VALUES ('79', '기타 기능 관련직');
INSERT INTO Occupation (occCode, occName) VALUES ('81', '식품가공 관련 기계 조작직');
INSERT INTO Occupation (occCode, occName) VALUES ('82', '섬유 및 신발 관련 기계 조작직');
INSERT INTO Occupation (occCode, occName) VALUES ('83', '화학 관련 기계 조작직');
INSERT INTO Occupation (occCode, occName) VALUES ('84', '금속 및 비금속 관련 기계 조작직');
INSERT INTO Occupation (occCode, occName) VALUES ('85', '기계제조 및 관련 기계 조작직');
INSERT INTO Occupation (occCode, occName) VALUES ('86', '전기 및 전자 관련 기계 조작직');
INSERT INTO Occupation (occCode, occName) VALUES ('87', '운전 및 운송 관련직');
INSERT INTO Occupation (occCode, occName) VALUES ('88', '상하수도 및 재활용 처리 관련 기계 조작직');
INSERT INTO Occupation (occCode, occName) VALUES ('89', '목재·인쇄 및 기타 기계 조작직');
INSERT INTO Occupation (occCode, occName) VALUES ('91', '건설 및 광업 관련 단순 노무직');
INSERT INTO Occupation (occCode, occName) VALUES ('92', '운송 관련 단순 노무직');
INSERT INTO Occupation (occCode, occName) VALUES ('93', '제조 관련 단순 노무직');
INSERT INTO Occupation (occCode, occName) VALUES ('94', '청소 및 경비 관련 단순 노무직');
INSERT INTO Occupation (occCode, occName) VALUES ('95', '가사·음식 및 판매 관련 단순노무직');
INSERT INTO Occupation (occCode, occName) VALUES ('99', '농림어업 및 기타 서비스 단순노무직');
INSERT INTO Occupation (occCode, occName) VALUES ('A01', '장교');
INSERT INTO Occupation (occCode, occName) VALUES ('A02', '부사관');
INSERT INTO Occupation (occCode, occName) VALUES ('A09', '기타 군인');
INSERT INTO Occupation (occCode, occName) VALUES ('1', '관리자');
INSERT INTO Occupation (occCode, occName) VALUES ('2', '전문가 및 관련 종사자');
INSERT INTO Occupation (occCode, occName) VALUES ('3', '서비스 종사자');
INSERT INTO Occupation (occCode, occName) VALUES ('4', '사무 종사자');
INSERT INTO Occupation (occCode, occName) VALUES ('5', '판매종사자');
INSERT INTO Occupation (occCode, occName) VALUES ('6', '농리농림·어업 숙련 종사자');
INSERT INTO Occupation (occCode, occName) VALUES ('7', '기능원 및 관련 기능 종사자');
INSERT INTO Occupation (occCode, occName) VALUES ('8', '장치·기계 조작 및 조립 종사자');
INSERT INTO Occupation (occCode, occName) VALUES ('9', '단순노무 종사자');
INSERT INTO Occupation (occCode, occName) VALUES ('A', '군인');
